apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-adlists
  namespace: pihole
data:
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-regex
  namespace: pihole
data:
  regex.list: |
    ^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-env
  namespace: pihole
data:
  TZ: UTC
  DNS1: 1.1.1.1
  DNS2: 1.0.0.1
