apiVersion: v1
kind: Service
metadata:
  name: pihole-service-tcp
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: "port-53"
    - protocol: TCP
      port: 9009
      targetPort: 80
      name: "pihold-web"
  externalTrafficPolicy: Local
  type: LoadBalancer
  externalIPs:
    - 10.0.0.9
  loadBalancerIP: 10.0.0.9
---

apiVersion: v1
kind: Service
metadata:
  name: pihole-service-udp
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: "port-53-udp"
    - protocol: UDP
      port: 67
      targetPort: 67
      name: "port-67"
  externalTrafficPolicy: Local
  type: LoadBalancer
  externalIPs:
    - 10.0.0.9
  loadBalancerIP: 10.0.0.9
