kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fin-minecraft-data
  namespace: fin
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
